name: tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  run-unit-tests:
    name: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'

      - name: Run unit tests
        run: go test ./...

